# Trigger the workflow on push and workflow dispatch to the PROD branch
name: Commercial CI/CD for PROD
on:
  workflow_dispatch:
  push:
    branches:
      - PROD

jobs:
  build:
    runs-on: ${{ vars.HOSTED_RUNNER_GITHUB }}
    steps:
      # Check out the repository code
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Use Node.js ${{ vars.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ vars.NODE_VERSION }}
        # Install npm dependencies
      - name: Install dependencies
        run: npm install
      - name: code build using npm
        run: npm run build:prod
      - name: list the build artifacts
        run:
          ls -alrth
          # Generate a deployment package for Elastic Beanstalk
      - name: Generate deployment package for EB
        run: zip -r ${{ github.ref_name }}-${{ github.run_number}}-reg-prod.zip .next public package.json package-lock.json
      - run: ls -alrth
        # Upload the deployment package as an artifacts
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          path: ${{ github.ref_name }}-${{ github.run_number}}-reg-prod.zip
          # Deploy the package to Elastic Beanstalk
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID_COMMERCIALS_PROD }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_COMMERCIALS_PROD }}
          application_name: ${{ vars.COMMERCIAL_EB_APP_NAME_PROD }}
          environment_name: ${{ vars.COMMERCIAL_EB_ENV_NAME_PROD }}
          version_label: ${{ github.ref_name }}-${{ github.run_number}}-reg-prod.zip
          region: ${{ vars.AWS_REGION_ACTIVE }}
          deployment_package: ${{ github.ref_name }}-${{ github.run_number}}-reg-prod.zip
